# Generated by Django 3.2.5 on 2022-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='mode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
